import type { NextPage } from "next";
import Head from "next/head";
import { DefaultLayout } from "../layouts/DefaultLayout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DefaultLayout>
        <div>
          <h1>Pixel Image</h1>
        </div>
        <div>
          <img
            src={`http://localhost:3000/api?image=https://images-fe.ssl-images-amazon.com/images/I/51YSzlNrzIL.jpg`}
            alt=""
          />
        </div>
      </DefaultLayout>
    </>
  );
};

export default Home;
